"""Public light-group configuration exports."""

from custom_components.magic_areas.light_groups.entities import (
    AreaLightGroup,
    MagicLightGroup,
)
from custom_components.magic_areas.light_groups.policy import (
    ActOnMode,
    CommandEchoState,
    LightAction,
    LightGroupPolicy,
    LightPolicySignals,
    build_light_control_group_policy,
    light_action_to_control_group,
)
from custom_components.magic_areas.light_groups.config import (
    CONF_OVERHEAD_LIGHTS,
    CONF_OVERHEAD_LIGHTS_ACT_ON,
    CONF_OVERHEAD_LIGHTS_STATES,
    CONF_TASK_LIGHTS,
    CONF_TASK_LIGHTS_ACT_ON,
    CONF_TASK_LIGHTS_STATES,
    LIGHT_GROUP_ACT_ON_OCCUPANCY_CHANGE,
    LIGHT_GROUP_ACT_ON_STATE_CHANGE,
    LIGHT_GROUP_FEATURE_SCHEMA,
    LIGHT_GROUP_PRESETS,
    light_groups_feature_config,
    preset_members,
    preset_states,
    get_light_group_preset,
)
from custom_components.magic_areas.light_groups.runtime import (
    is_valid_origin_state_toggle,
    process_secondary_group_state_change,
    turn_off,
    turn_on,
)
__all__ = [
    "AreaLightGroup",
    "CONF_OVERHEAD_LIGHTS",
    "CONF_OVERHEAD_LIGHTS_ACT_ON",
    "CONF_OVERHEAD_LIGHTS_STATES",
    "CONF_TASK_LIGHTS",
    "CONF_TASK_LIGHTS_ACT_ON",
    "CONF_TASK_LIGHTS_STATES",
    "ActOnMode",
    "CommandEchoState",
    "LIGHT_GROUP_ACT_ON_OCCUPANCY_CHANGE",
    "LIGHT_GROUP_ACT_ON_STATE_CHANGE",
    "LIGHT_GROUP_FEATURE_SCHEMA",
    "LIGHT_GROUP_PRESETS",
    "light_groups_feature_config",
    "preset_members",
    "preset_states",
    "get_light_group_preset",
    "is_valid_origin_state_toggle",
    "LightAction",
    "LightGroupPolicy",
    "LightPolicySignals",
    "MagicLightGroup",
    "process_secondary_group_state_change",
    "build_light_control_group_policy",
    "light_action_to_control_group",
    "turn_off",
    "turn_on",
]
