default_install_hook_types: [pre-commit, pre-push]

repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: uv run --extra dev --extra test ruff check --fix
        language: system
        stages: [pre-commit]
        types_or: [python, pyi]

      - id: ruff-format
        name: ruff format
        entry: uv run --extra dev --extra test ruff format
        language: system
        stages: [pre-commit]
        types_or: [python, pyi]

      - id: ruff-format-check
        name: ruff format check
        entry: uv run --extra dev --extra test ruff format --check custom_components tests
        language: system
        stages: [pre-push]
        pass_filenames: false
