"""Area state/type constants and derived lists."""

# Area States (string values used in config/state machine)
AREA_STATE_CLEAR = "clear"
AREA_STATE_OCCUPIED = "occupied"
AREA_STATE_EXTENDED = "extended"
AREA_STATE_DARK = "dark"
AREA_STATE_BRIGHT = "bright"
AREA_STATE_SLEEP = "sleep"
AREA_STATE_ACCENT = "accented"

AREA_PRIORITY_STATES = [AREA_STATE_SLEEP, AREA_STATE_ACCENT]

BUILTIN_AREA_STATES = [AREA_STATE_OCCUPIED, AREA_STATE_EXTENDED]
CONFIGURABLE_AREA_STATES = [AREA_STATE_DARK, AREA_STATE_ACCENT, AREA_STATE_SLEEP]

# Meta Areas (display names)
META_AREA_GLOBAL = "Global"
META_AREA_INTERIOR = "Interior"
META_AREA_EXTERIOR = "Exterior"
META_AREAS = [META_AREA_GLOBAL, META_AREA_INTERIOR, META_AREA_EXTERIOR]

# Area Types (string values)
AREA_TYPE_META = "meta"
AREA_TYPE_INTERIOR = "interior"
AREA_TYPE_EXTERIOR = "exterior"
AREA_TYPES = [AREA_TYPE_INTERIOR, AREA_TYPE_EXTERIOR, AREA_TYPE_META]
