"""Feature flag constants and feature lists."""

# features
CONF_FEATURE_CLIMATE_CONTROL = "climate_control"
CONF_FEATURE_FAN_GROUPS = "fan_groups"
CONF_FEATURE_MEDIA_PLAYER_GROUPS = "media_player_groups"
CONF_FEATURE_LIGHT_GROUPS = "light_groups"
CONF_FEATURE_COVER_GROUPS = "cover_groups"
CONF_FEATURE_AREA_AWARE_MEDIA_PLAYER = "area_aware_media_player"
CONF_FEATURE_AGGREGATION = "aggregates"
CONF_FEATURE_HEALTH = "health"
CONF_FEATURE_PRESENCE_HOLD = "presence_hold"
CONF_FEATURE_BLE_TRACKERS = "ble_trackers"
CONF_FEATURE_WASP_IN_A_BOX = "wasp_in_a_box"

CONF_FEATURE_LIST_META = [
    CONF_FEATURE_MEDIA_PLAYER_GROUPS,
    CONF_FEATURE_LIGHT_GROUPS,
    CONF_FEATURE_COVER_GROUPS,
    CONF_FEATURE_CLIMATE_CONTROL,
    CONF_FEATURE_AGGREGATION,
    CONF_FEATURE_HEALTH,
]

CONF_FEATURE_LIST = CONF_FEATURE_LIST_META + [
    CONF_FEATURE_AREA_AWARE_MEDIA_PLAYER,
    CONF_FEATURE_PRESENCE_HOLD,
    CONF_FEATURE_BLE_TRACKERS,
    CONF_FEATURE_FAN_GROUPS,
    CONF_FEATURE_WASP_IN_A_BOX,
]

CONF_FEATURE_LIST_GLOBAL = CONF_FEATURE_LIST_META
