"""Canonical default values for feature option keys."""

from __future__ import annotations

from custom_components.magic_areas.config_keys.area import (
    CONF_AGGREGATES_BINARY_SENSOR_DEVICE_CLASSES,
    CONF_AGGREGATES_ILLUMINANCE_THRESHOLD,
    CONF_AGGREGATES_ILLUMINANCE_THRESHOLD_HYSTERESIS,
    CONF_AGGREGATES_MIN_ENTITIES,
    CONF_AGGREGATES_SENSOR_DEVICE_CLASSES,
    CONF_BLE_TRACKER_ENTITIES,
    CONF_CLIMATE_CONTROL_PRESET_CLEAR,
    CONF_CLIMATE_CONTROL_PRESET_EXTENDED,
    CONF_CLIMATE_CONTROL_PRESET_OCCUPIED,
    CONF_CLIMATE_CONTROL_PRESET_SLEEP,
    CONF_FAN_GROUPS_REQUIRED_STATE,
    CONF_FAN_GROUPS_SETPOINT,
    CONF_FAN_GROUPS_TRACKED_DEVICE_CLASS,
    CONF_HEALTH_SENSOR_DEVICE_CLASSES,
    CONF_LIGHT_GROUP_BRIGHTNESS_MODE,
    CONF_LIGHT_GROUP_BRIGHT_DWELL_SECONDS,
    CONF_LIGHT_GROUP_BRIGHT_MIN_ON_SECONDS,
    CONF_LIGHT_GROUP_BRIGHT_ATTRIBUTION_HOLD_SECONDS,
    CONF_LIGHT_GROUP_ADAPTIVE_REQUIRE_AMBIENT_RISE,
    CONF_LIGHT_GROUP_AMBIENT_RISE_WINDOW_SECONDS,
    CONF_LIGHT_GROUP_AMBIENT_RISE_MIN_DELTA,
    CONF_LIGHT_GROUP_OUTSIDE_CONTEXT_SOURCE,
    CONF_LIGHT_GROUP_OUTSIDE_LUX_INSIDE_RATIO_MIN_PERCENT,
    CONF_LIGHT_GROUP_OUTSIDE_LUX_INSIDE_DELTA,
    CONF_LIGHT_GROUP_OUTSIDE_LUX_INSIDE_ENTITY,
    CONF_LIGHT_GROUP_OUTSIDE_LUX_ENTITY,
    CONF_LIGHT_GROUP_OUTSIDE_LUX_MIN,
    CONF_NOTIFICATION_DEVICES,
    CONF_NOTIFY_STATES,
    CONF_PRESENCE_HOLD_TIMEOUT,
    CONF_WASP_IN_A_BOX_DELAY,
    CONF_WASP_IN_A_BOX_WASP_DEVICE_CLASSES,
    CONF_WASP_IN_A_BOX_WASP_TIMEOUT,
)
from custom_components.magic_areas.defaults import (
    DEFAULT_AGGREGATES_BINARY_SENSOR_DEVICE_CLASSES,
    DEFAULT_AGGREGATES_ILLUMINANCE_THRESHOLD,
    DEFAULT_AGGREGATES_ILLUMINANCE_THRESHOLD_HYSTERESIS,
    DEFAULT_AGGREGATES_MIN_ENTITIES,
    DEFAULT_AGGREGATES_SENSOR_DEVICE_CLASSES,
    DEFAULT_CLIMATE_CONTROL_PRESET_CLEAR,
    DEFAULT_CLIMATE_CONTROL_PRESET_EXTENDED,
    DEFAULT_CLIMATE_CONTROL_PRESET_OCCUPIED,
    DEFAULT_CLIMATE_CONTROL_PRESET_SLEEP,
    DEFAULT_FAN_GROUPS_REQUIRED_STATE,
    DEFAULT_FAN_GROUPS_SETPOINT,
    DEFAULT_FAN_GROUPS_TRACKED_DEVICE_CLASS,
    DEFAULT_HEALTH_SENSOR_DEVICE_CLASSES,
    DEFAULT_NOTIFY_STATES,
    DEFAULT_PRESENCE_HOLD_TIMEOUT,
    DEFAULT_WASP_IN_A_BOX_DELAY,
    DEFAULT_WASP_IN_A_BOX_WASP_DEVICE_CLASSES,
    DEFAULT_WASP_IN_A_BOX_WASP_TIMEOUT,
)
from custom_components.magic_areas.enums import MagicAreasFeatures
FeatureOptionValue = object
FeatureOptionDefaults = dict[str, FeatureOptionValue]

FEATURE_OPTION_DEFAULTS: dict[MagicAreasFeatures, FeatureOptionDefaults] = {
    MagicAreasFeatures.AGGREGATES: {
        CONF_AGGREGATES_MIN_ENTITIES: DEFAULT_AGGREGATES_MIN_ENTITIES,
        CONF_AGGREGATES_BINARY_SENSOR_DEVICE_CLASSES: DEFAULT_AGGREGATES_BINARY_SENSOR_DEVICE_CLASSES,
        CONF_AGGREGATES_SENSOR_DEVICE_CLASSES: DEFAULT_AGGREGATES_SENSOR_DEVICE_CLASSES,
        CONF_AGGREGATES_ILLUMINANCE_THRESHOLD: DEFAULT_AGGREGATES_ILLUMINANCE_THRESHOLD,
        CONF_AGGREGATES_ILLUMINANCE_THRESHOLD_HYSTERESIS: DEFAULT_AGGREGATES_ILLUMINANCE_THRESHOLD_HYSTERESIS,
    },
    MagicAreasFeatures.AREA_AWARE_MEDIA_PLAYER: {
        CONF_NOTIFICATION_DEVICES: [],
        CONF_NOTIFY_STATES: DEFAULT_NOTIFY_STATES,
    },
    MagicAreasFeatures.BLE_TRACKER: {
        CONF_BLE_TRACKER_ENTITIES: [],
    },
    MagicAreasFeatures.CLIMATE_CONTROL: {
        CONF_CLIMATE_CONTROL_PRESET_CLEAR: DEFAULT_CLIMATE_CONTROL_PRESET_CLEAR,
        CONF_CLIMATE_CONTROL_PRESET_OCCUPIED: DEFAULT_CLIMATE_CONTROL_PRESET_OCCUPIED,
        CONF_CLIMATE_CONTROL_PRESET_SLEEP: DEFAULT_CLIMATE_CONTROL_PRESET_SLEEP,
        CONF_CLIMATE_CONTROL_PRESET_EXTENDED: DEFAULT_CLIMATE_CONTROL_PRESET_EXTENDED,
    },
    MagicAreasFeatures.FAN_GROUPS: {
        CONF_FAN_GROUPS_REQUIRED_STATE: DEFAULT_FAN_GROUPS_REQUIRED_STATE,
        CONF_FAN_GROUPS_TRACKED_DEVICE_CLASS: DEFAULT_FAN_GROUPS_TRACKED_DEVICE_CLASS,
        CONF_FAN_GROUPS_SETPOINT: DEFAULT_FAN_GROUPS_SETPOINT,
    },
    MagicAreasFeatures.HEALTH: {
        CONF_HEALTH_SENSOR_DEVICE_CLASSES: DEFAULT_HEALTH_SENSOR_DEVICE_CLASSES,
    },
    MagicAreasFeatures.LIGHT_GROUPS: {
        CONF_LIGHT_GROUP_BRIGHTNESS_MODE: "inhibit",
        CONF_LIGHT_GROUP_BRIGHT_MIN_ON_SECONDS: 0,
        CONF_LIGHT_GROUP_BRIGHT_DWELL_SECONDS: 0,
        CONF_LIGHT_GROUP_BRIGHT_ATTRIBUTION_HOLD_SECONDS: 0,
        CONF_LIGHT_GROUP_ADAPTIVE_REQUIRE_AMBIENT_RISE: False,
        CONF_LIGHT_GROUP_AMBIENT_RISE_WINDOW_SECONDS: 120,
        CONF_LIGHT_GROUP_AMBIENT_RISE_MIN_DELTA: 20,
        CONF_LIGHT_GROUP_OUTSIDE_CONTEXT_SOURCE: "sun",
        CONF_LIGHT_GROUP_OUTSIDE_LUX_ENTITY: "",
        CONF_LIGHT_GROUP_OUTSIDE_LUX_MIN: 0,
        CONF_LIGHT_GROUP_OUTSIDE_LUX_INSIDE_ENTITY: "",
        CONF_LIGHT_GROUP_OUTSIDE_LUX_INSIDE_DELTA: 0,
        CONF_LIGHT_GROUP_OUTSIDE_LUX_INSIDE_RATIO_MIN_PERCENT: 0,
    },
    MagicAreasFeatures.PRESENCE_HOLD: {
        CONF_PRESENCE_HOLD_TIMEOUT: DEFAULT_PRESENCE_HOLD_TIMEOUT,
    },
    MagicAreasFeatures.WASP_IN_A_BOX: {
        CONF_WASP_IN_A_BOX_DELAY: DEFAULT_WASP_IN_A_BOX_DELAY,
        CONF_WASP_IN_A_BOX_WASP_TIMEOUT: DEFAULT_WASP_IN_A_BOX_WASP_TIMEOUT,
        CONF_WASP_IN_A_BOX_WASP_DEVICE_CLASSES: DEFAULT_WASP_IN_A_BOX_WASP_DEVICE_CLASSES,
    },
}


def feature_option_default(
    feature: MagicAreasFeatures, key: str
) -> FeatureOptionValue:
    """Return canonical default value for a feature option key."""
    return FEATURE_OPTION_DEFAULTS[feature][key]
