"""Validation tuple lists used by options/config flows."""

from __future__ import annotations

import voluptuous as vol
from homeassistant.helpers import config_validation as cv

from custom_components.magic_areas.const import (
    CONF_TYPE, DEFAULT_TYPE, AREA_TYPE_INTERIOR, AREA_TYPE_EXTERIOR, \
    CONF_INCLUDE_ENTITIES, CONF_EXCLUDE_ENTITIES, CONF_RELOAD_ON_REGISTRY_CHANGE, DEFAULT_RELOAD_ON_REGISTRY_CHANGE, \
    CONF_IGNORE_DIAGNOSTIC_ENTITIES, DEFAULT_IGNORE_DIAGNOSTIC_ENTITIES, CONF_PRESENCE_DEVICE_PLATFORMS, \
    DEFAULT_PRESENCE_DEVICE_PLATFORMS, CONF_PRESENCE_SENSOR_DEVICE_CLASS, CONF_KEEP_ONLY_ENTITIES, CONF_CLEAR_TIMEOUT, \
    DEFAULT_CLEAR_TIMEOUT, CONF_DARK_ENTITY, CONF_ACCENT_ENTITY, CONF_SLEEP_ENTITY, CONF_SLEEP_TIMEOUT, \
    DEFAULT_SLEEP_TIMEOUT, CONF_EXTENDED_TIME, DEFAULT_EXTENDED_TIME, CONF_EXTENDED_TIMEOUT, DEFAULT_EXTENDED_TIMEOUT, \
    CONF_SECONDARY_STATES_CALCULATION_MODE, DEFAULT_SECONDARY_STATES_CALCULATION_MODE, AREA_STATE_OCCUPIED, \
    CONF_AGGREGATES_MIN_ENTITIES, DEFAULT_AGGREGATES_MIN_ENTITIES, CONF_AGGREGATES_BINARY_SENSOR_DEVICE_CLASSES, \
    CONF_AGGREGATES_SENSOR_DEVICE_CLASSES,
    CONF_AGGREGATES_ILLUMINANCE_THRESHOLD,
    DEFAULT_AGGREGATES_ILLUMINANCE_THRESHOLD, CONF_AGGREGATES_ILLUMINANCE_THRESHOLD_HYSTERESIS, \
    DEFAULT_AGGREGATES_ILLUMINANCE_THRESHOLD_HYSTERESIS, CONF_HEALTH_SENSOR_DEVICE_CLASSES, \
    DEFAULT_HEALTH_SENSOR_DEVICE_CLASSES, CONF_PRESENCE_HOLD_TIMEOUT, DEFAULT_PRESENCE_HOLD_TIMEOUT, \
    CONF_BLE_TRACKER_ENTITIES, DEFAULT_BLE_TRACKER_ENTITIES, CONF_WASP_IN_A_BOX_DELAY, DEFAULT_WASP_IN_A_BOX_DELAY, \
    CONF_WASP_IN_A_BOX_WASP_TIMEOUT, DEFAULT_WASP_IN_A_BOX_WASP_TIMEOUT, CONF_WASP_IN_A_BOX_WASP_DEVICE_CLASSES, \
     CONF_CLIMATE_CONTROL_ENTITY_ID, CONF_CLIMATE_CONTROL_PRESET_CLEAR, \
    DEFAULT_CLIMATE_CONTROL_PRESET_CLEAR, CONF_CLIMATE_CONTROL_PRESET_OCCUPIED, DEFAULT_CLIMATE_CONTROL_PRESET_OCCUPIED, \
    CONF_CLIMATE_CONTROL_PRESET_SLEEP, DEFAULT_CLIMATE_CONTROL_PRESET_SLEEP, CONF_CLIMATE_CONTROL_PRESET_EXTENDED, \
    DEFAULT_CLIMATE_CONTROL_PRESET_EXTENDED, CONF_FAN_GROUPS_REQUIRED_STATE, DEFAULT_FAN_GROUPS_REQUIRED_STATE, \
    CONF_FAN_GROUPS_TRACKED_DEVICE_CLASS,  CONF_FAN_GROUPS_SETPOINT, \
    DEFAULT_FAN_GROUPS_SETPOINT, CONF_NOTIFICATION_DEVICES, CONF_NOTIFY_STATES, DEFAULT_NOTIFY_STATES
)
from custom_components.magic_areas.policy import WASP_IN_A_BOX_WASP_DEVICE_CLASSES
from custom_components.magic_areas.defaults import (
    DEFAULT_PRESENCE_DEVICE_SENSOR_CLASS,
    DEFAULT_AGGREGATES_BINARY_SENSOR_DEVICE_CLASSES,
    DEFAULT_AGGREGATES_SENSOR_DEVICE_CLASSES,
    DEFAULT_WASP_IN_A_BOX_WASP_DEVICE_CLASSES,
    DEFAULT_FAN_GROUPS_TRACKED_DEVICE_CLASS,
)
from custom_components.magic_areas.light_groups import (
    # light group
    CONF_OVERHEAD_LIGHTS,
    CONF_OVERHEAD_LIGHTS_STATES,
    CONF_OVERHEAD_LIGHTS_ACT_ON,
    CONF_SLEEP_LIGHTS,
    CONF_SLEEP_LIGHTS_STATES,
    CONF_SLEEP_LIGHTS_ACT_ON,
    CONF_ACCENT_LIGHTS,
    CONF_ACCENT_LIGHTS_STATES,
    CONF_ACCENT_LIGHTS_ACT_ON,
    CONF_TASK_LIGHTS,
    CONF_TASK_LIGHTS_STATES,
    CONF_TASK_LIGHTS_ACT_ON,
    DEFAULT_LIGHT_GROUP_ACT_ON,
)

OPTIONS_AREA = [
    (CONF_TYPE, DEFAULT_TYPE, vol.In([AREA_TYPE_INTERIOR, AREA_TYPE_EXTERIOR])),
    (CONF_INCLUDE_ENTITIES, [], cv.entity_ids),
    (CONF_EXCLUDE_ENTITIES, [], cv.entity_ids),
    (CONF_RELOAD_ON_REGISTRY_CHANGE, DEFAULT_RELOAD_ON_REGISTRY_CHANGE, cv.boolean),
    (CONF_IGNORE_DIAGNOSTIC_ENTITIES, DEFAULT_IGNORE_DIAGNOSTIC_ENTITIES, cv.boolean),
]

OPTIONS_PRESENCE_TRACKING = [
    (CONF_PRESENCE_DEVICE_PLATFORMS, DEFAULT_PRESENCE_DEVICE_PLATFORMS, cv.ensure_list),
    (CONF_PRESENCE_SENSOR_DEVICE_CLASS, DEFAULT_PRESENCE_DEVICE_SENSOR_CLASS, cv.ensure_list),
    (CONF_KEEP_ONLY_ENTITIES, [], cv.entity_ids),
    (CONF_CLEAR_TIMEOUT, DEFAULT_CLEAR_TIMEOUT, int),
]

OPTIONS_AREA_META = [
    (CONF_EXCLUDE_ENTITIES, [], cv.entity_ids),
    (CONF_RELOAD_ON_REGISTRY_CHANGE, DEFAULT_RELOAD_ON_REGISTRY_CHANGE, cv.boolean),
]

OPTIONS_PRESENCE_TRACKING_META = [
    (CONF_CLEAR_TIMEOUT, DEFAULT_CLEAR_TIMEOUT, int),
]

OPTIONS_SECONDARY_STATES = [
    (CONF_DARK_ENTITY, "", cv.entity_id),
    (CONF_ACCENT_ENTITY, "", cv.entity_id),
    (CONF_SLEEP_ENTITY, "", cv.entity_id),
    (CONF_SLEEP_TIMEOUT, DEFAULT_SLEEP_TIMEOUT, int),
    (CONF_EXTENDED_TIME, DEFAULT_EXTENDED_TIME, int),
    (CONF_EXTENDED_TIMEOUT, DEFAULT_EXTENDED_TIMEOUT, int),
]

OPTIONS_SECONDARY_STATES_META = [
    (CONF_SLEEP_TIMEOUT, DEFAULT_SLEEP_TIMEOUT, int),
    (CONF_EXTENDED_TIME, DEFAULT_EXTENDED_TIME, int),
    (CONF_EXTENDED_TIMEOUT, DEFAULT_EXTENDED_TIMEOUT, int),
    (CONF_SECONDARY_STATES_CALCULATION_MODE, DEFAULT_SECONDARY_STATES_CALCULATION_MODE, str),
]

OPTIONS_LIGHT_GROUP = [
    (CONF_OVERHEAD_LIGHTS, [], cv.entity_ids),
    (CONF_OVERHEAD_LIGHTS_STATES, [AREA_STATE_OCCUPIED], cv.ensure_list),
    (CONF_OVERHEAD_LIGHTS_ACT_ON, DEFAULT_LIGHT_GROUP_ACT_ON, cv.ensure_list),
    (CONF_SLEEP_LIGHTS, [], cv.entity_ids),
    (CONF_SLEEP_LIGHTS_STATES, [], cv.ensure_list),
    (CONF_SLEEP_LIGHTS_ACT_ON, DEFAULT_LIGHT_GROUP_ACT_ON, cv.ensure_list),
    (CONF_ACCENT_LIGHTS, [], cv.entity_ids),
    (CONF_ACCENT_LIGHTS_STATES, [], cv.ensure_list),
    (CONF_ACCENT_LIGHTS_ACT_ON, DEFAULT_LIGHT_GROUP_ACT_ON, cv.ensure_list),
    (CONF_TASK_LIGHTS, [], cv.entity_ids),
    (CONF_TASK_LIGHTS_STATES, [], cv.ensure_list),
    (CONF_TASK_LIGHTS_ACT_ON, DEFAULT_LIGHT_GROUP_ACT_ON, cv.ensure_list),
]

OPTIONS_AGGREGATES = [
    (CONF_AGGREGATES_MIN_ENTITIES, DEFAULT_AGGREGATES_MIN_ENTITIES, int),
    (CONF_AGGREGATES_BINARY_SENSOR_DEVICE_CLASSES, DEFAULT_AGGREGATES_BINARY_SENSOR_DEVICE_CLASSES, cv.ensure_list),
    (CONF_AGGREGATES_SENSOR_DEVICE_CLASSES, DEFAULT_AGGREGATES_SENSOR_DEVICE_CLASSES, cv.ensure_list),
    (CONF_AGGREGATES_ILLUMINANCE_THRESHOLD, DEFAULT_AGGREGATES_ILLUMINANCE_THRESHOLD, int),
    (CONF_AGGREGATES_ILLUMINANCE_THRESHOLD_HYSTERESIS, DEFAULT_AGGREGATES_ILLUMINANCE_THRESHOLD_HYSTERESIS, int),
]

OPTIONS_HEALTH_SENSOR = [
    (CONF_HEALTH_SENSOR_DEVICE_CLASSES, DEFAULT_HEALTH_SENSOR_DEVICE_CLASSES, cv.ensure_list),
]

OPTIONS_PRESENCE_HOLD = [
    (CONF_PRESENCE_HOLD_TIMEOUT, DEFAULT_PRESENCE_HOLD_TIMEOUT, int),
]

OPTIONS_BLE_TRACKERS = [
    (CONF_BLE_TRACKER_ENTITIES, DEFAULT_BLE_TRACKER_ENTITIES, cv.entity_ids),
]

OPTIONS_WASP_IN_A_BOX = [
    (CONF_WASP_IN_A_BOX_DELAY, DEFAULT_WASP_IN_A_BOX_DELAY, cv.positive_int),
    (CONF_WASP_IN_A_BOX_WASP_TIMEOUT, DEFAULT_WASP_IN_A_BOX_WASP_TIMEOUT, cv.positive_int),
    (
        CONF_WASP_IN_A_BOX_WASP_DEVICE_CLASSES,
        DEFAULT_WASP_IN_A_BOX_WASP_DEVICE_CLASSES,
        vol.In(WASP_IN_A_BOX_WASP_DEVICE_CLASSES),
    ),
]

OPTIONS_CLIMATE_CONTROL_ENTITY_SELECT = [
    (CONF_CLIMATE_CONTROL_ENTITY_ID, None, cv.entity_id),
]

OPTIONS_CLIMATE_CONTROL = [
    (CONF_CLIMATE_CONTROL_PRESET_CLEAR, DEFAULT_CLIMATE_CONTROL_PRESET_CLEAR, str),
    (CONF_CLIMATE_CONTROL_PRESET_OCCUPIED, DEFAULT_CLIMATE_CONTROL_PRESET_OCCUPIED, str),
    (CONF_CLIMATE_CONTROL_PRESET_SLEEP, DEFAULT_CLIMATE_CONTROL_PRESET_SLEEP, str),
    (CONF_CLIMATE_CONTROL_PRESET_EXTENDED, DEFAULT_CLIMATE_CONTROL_PRESET_EXTENDED, str),
]

OPTIONS_FAN_GROUP = [
    (CONF_FAN_GROUPS_REQUIRED_STATE, DEFAULT_FAN_GROUPS_REQUIRED_STATE, str),
    (CONF_FAN_GROUPS_TRACKED_DEVICE_CLASS, DEFAULT_FAN_GROUPS_TRACKED_DEVICE_CLASS, str),
    (CONF_FAN_GROUPS_SETPOINT, DEFAULT_FAN_GROUPS_SETPOINT, float),
]

OPTIONS_AREA_AWARE_MEDIA_PLAYER = [
    (CONF_NOTIFICATION_DEVICES, [], cv.entity_ids),
    (CONF_NOTIFY_STATES, DEFAULT_NOTIFY_STATES, cv.ensure_list),
]
