"""Control intent engine contracts."""

from custom_components.magic_areas.core.control_intents.adaptive_lighting import (
    ADAPT_BRIGHTNESS_SWITCH,
    ADAPT_COLOR_SWITCH,
    ADAPTIVE_LIGHTING_DOMAIN,
    ATTR_LIGHTS,
    MAIN_SWITCH,
    SERVICE_SET_MANUAL_CONTROL,
    SERVICE_TURN_OFF,
    SERVICE_TURN_ON,
    SLEEP_SWITCH,
    AdaptiveLightingCoordinationReason,
    AdaptiveLightingServiceIntent,
    AdaptiveLightingSwitchCandidate,
    AdaptiveLightingSwitchSet,
    adaptive_lighting_accent_adaptation_intents,
    adaptive_lighting_apply_data,
    adaptive_lighting_change_switch_settings_data,
    adaptive_lighting_manual_control_data,
    adaptive_lighting_manual_restore_intents,
    adaptive_lighting_sleep_switch_intents,
    adaptive_lighting_switch_entity_ids,
    switch_set_from_discovery_candidates,
    switch_set_from_explicit_refs,
    switch_set_from_name_candidates,
)
from custom_components.magic_areas.core.control_intents.adaptive_lighting_registry import (
    switch_set_from_hass_registry,
)
from custom_components.magic_areas.core.control_intents.adaptive_lighting_executor import (
    async_execute_adaptive_lighting_intents,
)
from custom_components.magic_areas.core.control_intents.engine import (
    ConstraintEffect,
    ControlIntent,
    IntentAction,
    IntentConstraint,
    IntentDecision,
    IntentReason,
    evaluate_intent,
)
from custom_components.magic_areas.core.control_intents.models import (
    ControlTargetKind,
    ControlTargetPrecision,
    ControlTargetSource,
    RoleTarget,
)
from custom_components.magic_areas.core.control_intents.targets import (
    custom_control_label_name,
    resolve_custom_control_target,
    resolve_role_target,
)

__all__ = [
    "ADAPT_BRIGHTNESS_SWITCH",
    "ADAPT_COLOR_SWITCH",
    "ADAPTIVE_LIGHTING_DOMAIN",
    "ATTR_LIGHTS",
    "MAIN_SWITCH",
    "SERVICE_SET_MANUAL_CONTROL",
    "SERVICE_TURN_OFF",
    "SERVICE_TURN_ON",
    "SLEEP_SWITCH",
    "AdaptiveLightingCoordinationReason",
    "AdaptiveLightingServiceIntent",
    "AdaptiveLightingSwitchCandidate",
    "AdaptiveLightingSwitchSet",
    "ConstraintEffect",
    "ControlIntent",
    "ControlTargetKind",
    "ControlTargetPrecision",
    "ControlTargetSource",
    "IntentAction",
    "IntentConstraint",
    "IntentDecision",
    "IntentReason",
    "RoleTarget",
    "adaptive_lighting_accent_adaptation_intents",
    "adaptive_lighting_apply_data",
    "adaptive_lighting_change_switch_settings_data",
    "adaptive_lighting_manual_control_data",
    "adaptive_lighting_manual_restore_intents",
    "adaptive_lighting_sleep_switch_intents",
    "adaptive_lighting_switch_entity_ids",
    "async_execute_adaptive_lighting_intents",
    "custom_control_label_name",
    "evaluate_intent",
    "resolve_custom_control_target",
    "resolve_role_target",
    "switch_set_from_discovery_candidates",
    "switch_set_from_explicit_refs",
    "switch_set_from_hass_registry",
    "switch_set_from_name_candidates",
]
